version: "3.8"

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ecommerce_clothing
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "sleep 2 && mysqladmin ping -h localhost -psecret"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - ecommerce-network
    volumes:
      - mysql-data:/var/lib/mysql

  ecommerce-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ecommerce-app
    depends_on:
      mysql-db:
        condition: service_healthy
    ports:
      - "7073:7073"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  mysql-data: